site_name: Nexara Protocol
site_description: Ethical Governance, Financial Sovereignty, and Incorruptible Automation
site_author: MJ Ahmad
repo_url: https://github.com/your-org/nexara-protocol
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.action.edit

nav:
  - Home: index.md
  - Constitution: constitution.md
  - Whitepaper: whitepaper.md
  - Roadmap: roadmap.md
  - Glossary: glossary.md
  - Governance:
      - Visionary Roles: visionary-roles.md
      - Persona Consistency: persona-consistency.md
      - Proposal Template: governance/proposal-template.md
      - Decision Tree: governance/decision-tree.md
      - Voting Policy: governance/voting-policy.md
      - Emergency Protocol: governance/emergency-protocol.md
      - Ratification Process: governance/ratification-process.md
      - Ratified Actions: governance/ratified-actions.md
  - Treasury:
      - Treasury Policy: ../nexara-treasury/README.md
      - Purpose Registry: treasury/purpose-registry.md
      - Disbursement Log: treasury/disbursement-log.md
  - Merit System: merit-policy.md
  - Security:
      - Threat Model: security/threat-model.md
      - Audit Log Policy: security/audit-log-policy.md
      - Incident Response: security/incident-response.md
      - Guardian Handbook: security/guardian-handbook.md
  - Ethics Manifesto: ethics.md
  - Community:
      - Community Charter: community-charter.md
      - FAQ: faq.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

plugins:
  - search
  - git-revision-date
